### ISSUE TITLE
Select i18n mechanism

### ISSUE THREAD

**Issue by msavy** [apiman/apiman-developer-portal#30]
Choose which i18n mechanism we'll use for portal v2 (e.g. inbuilt/recommended mechanism or some external library). Whatever is best practice.

**Comment by julian-eins** [comment]
As we discussed on last Wednesday we will use [ngx-translate](https://github.com/ngx-translate/core)

Reasons:

- We have experience with it
- Easy to configure
- Organizing language keys and translations in nested JSON objects (angular/localize uses xuml)
- Change language during runtime
- Large community
