### ISSUE TITLE
Filter for Your APIs

### ISSUE THREAD

**Issue by agebert** [apiman/apiman-developer-portal#34]
I have a feature request.

We have a convention that related APIs have the same prefix and would like to open the **Your APIs** with a filter to only display the relevant APIs. 
In my case something like ".../devportal/?filter=Trebeg / testTable-*" (values are not URL encoded).

![grafik](https://user-images.githubusercontent.com/2894/132367447-8c35d8c9-98a9-4ae0-b19e-1927da4852a0.png)

**Comment by volkflo** [comment]
Will not be done because of the new developement portal coming with apiman 3.x
