### ISSUE TITLE
API Policies are displayed in plan cards (details page)

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman-developer-portal#46]
At the moment if a plan has no (only one policy) the policies of the API itself are displayed in the Plan Card.

We should discuss if we display api policies at all or put them in a new section e.g. "global policies".

This is related to https://github.com/apiman/apiman/issues/1555

**Comment by msavy** [comment]
Should we only display plan policies? Are there cases where we really need to display API policies?

**Comment by volkflo** [comment]
I think it would be easier to display only plan policies or we have to find a way to integrate clients/api policies as well.
You could use an api policy like a master policy that applies for all plans. Could be interesting in the future. 
But I think for now we should only go with one, would make endpoints also easier to maintain.

**Comment by volkflo** [comment]
I think we discussed that we will only display plan policies for now. 
I will close this.
