### ISSUE TITLE
Reload of API Documentation does not work (Developer Portal v1)

### ISSUE THREAD

**Issue by BastianGem** [apiman/apiman-developer-portal#51]
**This bug only affects the Developer Portal version 1**

Loading the Swagger file via the 'Try API' button works fine.
But as soon as you trigger a browser reload (e.g. F5) you get a 404 error, because the swagger file cannot be loaded.
To get the Swagger file again you have to use the Try Api button from the API list.

Maybe this bug will not be fixed anymore, depending on when version 1 will be completely replaced.

**Comment by volkflo** [comment]
@msavy I think we can close this because of the upcoming v2 release.
I changed that in v2 so that its save to reload the page.

**Comment by volkflo** [comment]
Will not be fixed for the v1 of the developer portal.
Fixed in the new version for Apiman 3.x
