### ISSUE TITLE
Get locale from token and browser settings

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman-developer-portal#55]
### Current
We read the default language from the config which is applied then.

### Idea 
Read the language from browser and token and then fallback to default config.

### Acceptance
The language should be fetched from the browser settings or the token.
If one of that fails we should fallback to the default from the config file if the language is not available.

**Comment by msavy** [comment]
Locale will be available from the backend config

**Comment by msavy** [comment]
https://github.com/apiman/apiman/pull/1657

**Comment by msavy** [comment]
I would suggest you need to just have a language picker to override the inferred locale, and then store it in the user's profile. Can talk more about this when I get back.
