### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by volkflo** [apiman/apiman-developer-portal#8]
@bekihm Was there a reason why you used the environment variables via injection instead of the environment import?
With the second way, there is no need to set the variables via the constructor. I tested this and the variable substitution still works.

![image](https://user-images.githubusercontent.com/13332383/96717800-587d3980-13a7-11eb-9252-068951851bb6.png)

**Comment by bekihm** [comment]
@volkflo I think it was just a matter of taste. The angular tutorials suggested injection as mechanism to share information between components.

**Comment by volkflo** [comment]
Thanks for the information :)
The current documentation does not use Injection anymore. So I may restructure this :)
https://angular.io/guide/build#using-environment-specific-variables-in-your-app

**Comment by bekihm** [comment]
@volkflo Ok :-) You may also keep the main branch free from fixup commits by squashing ;-)

**Comment by volkflo** [comment]
Oh crap! You are right about this. I just pressed the merge button this morning and did not remember that I had pushed fixups :/

**Comment by bekihm** [comment]
Just a hint :-)
