### ISSUE TITLE
My clients: If a client doesn't have a contract, it doesn't appear

### ISSUE THREAD

**Issue by msavy** [apiman/apiman-developer-portal#95]
I know this is a currently known limitation, but I want to document it.

## Reproduction steps
- In main Apiman UI create a client, but don't create a contract yet.
- In devportal go to "my clients" page, it will be blank/empty
- In main Apiman UI, create a contract
- In devportal go to "my clients" page, it will have appeared

## Acceptance criteria
- Client should appear if it has been created (via API or whatever), even if there are not yet any contracts. 
- Show an appropriate message of some sort indicating that 'empty' status.

**Comment by volkflo** [comment]
Fixed in main
